# Generated by Django 6.0.7 on 2026-07-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.CharField(db_index=True, help_text='Código IBGE do município, 7 dígitos.', max_length=7, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=150)),
                ('uf', models.CharField(db_index=True, max_length=2)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome', 'uf'], name='municipios__nome_96f65f_idx')],
            },
        ),
    ]
