# Generated by Django 6.0.7 on 2026-07-23 02:37

from django.db import migrations, models


def backfill_nome_normalizado(apps, schema_editor):
    """
    Popula nome_normalizado para linhas já existentes (ex.: bancos onde
    import_municipios já rodou antes desta migration). Registros criados
    a partir de agora já chegam com o campo preenchido via Municipio.save().
    """
    Municipio = apps.get_model('municipios', 'Municipio')
    from municipios.models import normalizar_texto

    for municipio in Municipio.objects.all().iterator():
        municipio.nome_normalizado = normalizar_texto(municipio.nome)
        municipio.save(update_fields=['nome_normalizado'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='nome_normalizado',
            field=models.CharField(blank=True, db_index=True, help_text='`nome` sem acento e em minúsculas — mantido em sync via save(), usado só para busca tolerante a acentuação.', max_length=150),
        ),
        migrations.RunPython(backfill_nome_normalizado, noop),
    ]
