# Generated by Django 6.0.6 on 2026-07-13 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_clinicuser'),
        ('clinics', '0007_clinic_asaas_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entities_scope', models.JSONField(blank=True, default=list)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('key_delivered', 'Chave entregue ao gateway'), ('syncing', 'Sincronizando'), ('ready', 'Pronto'), ('expired', 'Expirado')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sessions', to='clinics.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_sessions_created', to='accounts.clinicuser')),
            ],
            options={
                'verbose_name': 'Sessão de Relatório',
                'verbose_name_plural': 'Sessões de Relatório',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'status'], name='portal_gest_clinic__a84fde_idx')],
            },
        ),
    ]
