# Generated by Django 6.0.6 on 2026-07-13 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clinicuser'),
        ('portal_gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True, help_text='Kill-switch manual — desativa sem precisar apagar.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aviso do Produto',
                'verbose_name_plural': 'Avisos do Produto',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicUserNoticeDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('clinic_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_dismissals', to='accounts.clinicuser')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='portal_gestor.productnotice')),
            ],
            options={
                'verbose_name': 'Dispensa de Aviso',
                'verbose_name_plural': 'Dispensas de Aviso',
                'unique_together': {('clinic_user', 'notice')},
            },
        ),
    ]
