# Generated by Django 6.0.6 on 2026-07-17 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clinicuser'),
        ('clinics', '0008_clinic_desconto_fidelidade_ano2_and_more'),
        ('portal_gestor', '0002_productnotice_clinicusernoticedismissal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalReadAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(help_text='session_id da ReportSession que autorizou a leitura (não é FK — a sessão pode expirar/ser limpa sem apagar o log de auditoria).')),
                ('entity', models.CharField(help_text="Entidade acessada: 'patients', 'appointments' ou 'professionals'.", max_length=32)),
                ('record_count', models.PositiveIntegerField(help_text='Quantidade de registros retornados pela leitura — pode ser 0.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_read_audit_logs', to='clinics.clinic')),
                ('clinic_user', models.ForeignKey(help_text='Nulo se o usuário for removido depois — o registro de auditoria não pode desaparecer com ele.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_read_audit_logs', to='accounts.clinicuser')),
            ],
            options={
                'verbose_name': 'Log de Auditoria de Leitura',
                'verbose_name_plural': 'Logs de Auditoria de Leitura',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'created_at'], name='portal_gest_clinic__67a57c_idx'), models.Index(fields=['session_id'], name='portal_gest_session_29bc0a_idx')],
            },
        ),
    ]
