# Generated by Django 6.0.8 on 2026-10-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_gestor', '0003_portalreadauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalreadauditlog',
            name='entity',
            field=models.CharField(help_text="Entidade acessada: 'patients', 'appointments', 'professionals', 'medical_records', 'billing' ou 'support_ticket'.", max_length=32),
        ),
    ]
