# Generated by Django 6.0.7 on 2026-07-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('NACIONAL', 'Nacional'), ('ESTADUAL', 'Estadual'), ('MUNICIPAL', 'Municipal')], max_length=20)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('ibge_code', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('year', models.IntegerField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'type', 'ibge_code')},
            },
        ),
    ]
