# Generated by Django 6.0.8 on 2026-10-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoBusca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge_code', models.CharField(max_length=7)),
                ('year', models.IntegerField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Busca de feriados',
                'verbose_name_plural': 'Buscas de feriados',
                'constraints': [models.UniqueConstraint(fields=('ibge_code', 'year'), name='uniq_feriado_busca_ibge_year')],
            },
        ),
    ]
