# Generated by Django 6.0.8 on 2026-10-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_feriado_busca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feriado',
            options={'ordering': ['date'], 'verbose_name': 'Feriado', 'verbose_name_plural': 'Feriados'},
        ),
        migrations.AlterField(
            model_name='feriado',
            name='date',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='ibge_code',
            field=models.CharField(blank=True, db_index=True, help_text='Obrigatório para feriado municipal, 7 dígitos. Ex.: Osasco = 3534401.', max_length=7, null=True, verbose_name='código IBGE do município'),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='name',
            field=models.CharField(max_length=150, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='type',
            field=models.CharField(choices=[('NACIONAL', 'Nacional'), ('ESTADUAL', 'Estadual'), ('MUNICIPAL', 'Municipal')], max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='uf',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], help_text='Obrigatória para feriado estadual. Para municipal é preenchida automaticamente a partir do código IBGE. Ignorada para nacional.', max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='year',
            field=models.IntegerField(db_index=True, help_text='Derivado automaticamente da data.', verbose_name='ano'),
        ),
    ]
