# Generated by Django 6.0.7 on 2026-08-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.CharField(db_index=True, help_text='Código IBGE do município, 7 dígitos. NÃO é único: um mesmo município tem muitos CEPs (linhas) apontando para o mesmo `codigo_ibge` — a unicidade real desta tabela é por `cep`.', max_length=7)),
                ('cep', models.CharField(db_index=True, help_text='CEP do município, 8 dígitos + hífen opcional.', max_length=9, unique=True)),
                ('logradouro', models.CharField(blank=True, help_text="Logradouro do CEP, se houver (ex.: 'Rua das Flores').", max_length=250)),
                ('bairro', models.CharField(blank=True, help_text="Bairro do CEP, se houver (ex.: 'Jardim das Acácias').", max_length=250)),
                ('localidade', models.CharField(blank=True, help_text="Localidade do CEP, se houver (ex.: 'São Paulo').", max_length=250)),
                ('estado', models.CharField(blank=True, help_text="Estado do CEP, se houver (ex.: 'São Paulo').", max_length=250)),
                ('regiao', models.CharField(blank=True, help_text="Região do CEP, se houver (ex.: 'Sudeste').", max_length=250)),
                ('uf', models.CharField(db_index=True, max_length=2)),
                ('logradouro_normalizado', models.CharField(blank=True, db_index=True, help_text='`logradouro` sem acento e em minúsculas — mantido em sync via save(), usado só para busca tolerante a acentuação.', max_length=250)),
                ('estado_normalizado', models.CharField(blank=True, db_index=True, help_text='`estado` sem acento e em minúsculas — mantido em sync via save(), usado só para busca tolerante a acentuação.', max_length=250)),
                ('cidade_normalizada', models.CharField(blank=True, db_index=True, help_text='`localidade` sem acento e em minúsculas — mantido em sync via save(), usado só para busca tolerante a acentuação.', max_length=250)),
                ('gia', models.CharField(blank=True, help_text="Código GIA do município, se houver (ex.: '1004').", max_length=4)),
                ('ddd', models.CharField(blank=True, help_text="DDD do município, se houver (ex.: '11').", max_length=2)),
                ('siafi', models.CharField(blank=True, help_text="Código SIAFI do município, se houver (ex.: '7107').", max_length=4)),
            ],
            options={
                'ordering': ['cep'],
                'indexes': [models.Index(fields=['cep', 'uf'], name='zipcode_cep_cep_f7c08a_idx')],
            },
        ),
    ]
