# Generated by Django 6.0.6 on 2026-06-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='db_name',
            field=models.CharField(blank=True, max_length=63, unique=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='db_user',
            field=models.CharField(blank=True, max_length=63, unique=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='provisioning_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='provisioning_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('provisioned', 'Provisionado'), ('failed', 'Falhou')], default='pending', max_length=20),
        ),
    ]
