# Generated by Django 6.0.6 on 2026-06-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_db_name_clinic_db_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='db_password_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='public_key_pem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='provisioning_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('waiting_key', 'Aguardando chave pública'), ('provisioned', 'Provisionado'), ('failed', 'Falhou')], default='waiting_key', max_length=20),
        ),
    ]
