# Generated by Django 6.0.6 on 2026-06-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinic_db_password_encrypted_clinic_public_key_pem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, unique=True),
        ),
    ]
