# Generated by Django 6.0.6 on 2026-06-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_add_cnpj_to_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='license_expires_at',
            field=models.DateTimeField(blank=True, help_text='Data de expiração da licença', null=True),
        ),
    ]
