# Generated by Django 6.0.6 on 2026-07-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_clinic_license_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='active_modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clinic',
            name='gateway_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
