# Generated by Django 6.0.6 on 2026-07-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_clinic_active_modules_clinic_gateway_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='asaas_subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
