# Generated by Django 6.0.6 on 2026-07-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_clinic_asaas_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='desconto_fidelidade_ano2',
            field=models.BooleanField(default=False, help_text='Decisão manual de CS: mantém o desconto no 2º ano em diante. Não é calculado automaticamente — julgamento qualitativo sobre engajamento/feedback da clínica durante o 1º ano.'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='preco_promocional',
            field=models.BooleanField(default=False, help_text='Desconto de lançamento (R$99,90/mês no 1º ano) — limitado às 30 primeiras clínicas.'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='price_adjusted_at',
            field=models.DateTimeField(blank=True, help_text='Marca quando o job de reajuste de 12 meses já processou esta clínica (evita reajuste duplicado).', null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='subscription_started_at',
            field=models.DateTimeField(blank=True, help_text='Data de início da assinatura recorrente no Asaas (base para o aniversário de 12 meses).', null=True),
        ),
    ]
