# Generated by Django 6.0.7 on 2026-07-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_clinic_desconto_fidelidade_ano2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='support_ticket_restricted_to_admin',
            field=models.BooleanField(default=False, help_text='Restringe criação/visualização de tickets de suporte ao admin da clínica (BACFF-AVULSA-09).'),
        ),
    ]
