# Generated by Django 6.0.7 on 2026-08-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_clinic_support_ticket_restricted_to_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='cnes',
            field=models.CharField(blank=True, db_default='', default='', help_text='Código CNES (Cadastro Nacional de Estabelecimentos de Saúde), 7 dígitos numéricos — obrigatório para geração de guias TISS.', max_length=7),
        ),
    ]
