# Generated by Django 6.0.6 on 2026-06-29 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clinics', '0004_add_cnpj_to_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('viewer', 'Visualizador')], default='viewer', help_text='Nível de permissão (owner/admin/viewer)', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(help_text='Clínica que pode acessar', on_delete=django.db.models.deletion.CASCADE, related_name='admin_accesses', to='clinics.clinic')),
                ('granted_by', models.ForeignKey(help_text='Quem concedeu acesso (para auditoria)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_accesses_granted', to=settings.AUTH_USER_MODEL)),
                ('support_user', models.ForeignKey(help_text='Usuário que tem acesso', on_delete=django.db.models.deletion.CASCADE, related_name='clinic_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso de Clínica',
                'verbose_name_plural': 'Acessos de Clínica',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['support_user', 'role'], name='accounts_cl_support_9701f5_idx'), models.Index(fields=['clinic', 'role'], name='accounts_cl_clinic__b9c0ca_idx')],
                'unique_together': {('support_user', 'clinic')},
            },
        ),
    ]
