# Generated by Django 6.0.6 on 2026-07-13 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clinicaccess'),
        ('clinics', '0007_clinic_asaas_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, help_text='Hash da senha (auth_provider=local)', max_length=255)),
                ('auth_provider', models.CharField(choices=[('local', 'Local (email/senha)'), ('ldap', 'LDAP (add-on pago, não implementado)')], default='local', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(help_text='Clínica à qual este usuário pertence — nunca enxerga outra.', on_delete=django.db.models.deletion.CASCADE, related_name='clinic_users', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Usuário da Clínica',
                'verbose_name_plural': 'Usuários da Clínica',
                'indexes': [models.Index(fields=['clinic', 'email'], name='accounts_cl_clinic__d5fb0c_idx')],
                'unique_together': {('clinic', 'email')},
            },
        ),
    ]
