# Generated by Django 6.0.6 on 2026-06-29 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_add_cnpj_to_clinic'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'permissions': [('can_assign_ticket', 'Pode atribuir tickets a membros'), ('can_resolve_ticket', 'Pode marcar ticket como resolvido')], 'verbose_name': 'Ticket de Suporte', 'verbose_name_plural': 'Tickets de Suporte'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Mensagem de Ticket', 'verbose_name_plural': 'Mensagens de Ticket'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Quem está resolvendo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='clinic',
            field=models.ForeignKey(help_text='Clínica que reportou o problema', on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(help_text='Quem criou o ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(help_text='Descrição detalhada'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notion_page_id',
            field=models.CharField(blank=True, help_text='UUID da página no Notion (para sincronização)', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', help_text='Nível de urgência', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora que foi resolvido', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em Progresso'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], default='open', help_text='Estado atual', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(help_text='Título do problema', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='author',
            field=models.ForeignKey(help_text='Autor da mensagem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='message',
            field=models.TextField(help_text='Conteúdo da mensagem'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(help_text='Ticket ao qual a mensagem pertence', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['clinic', '-created_at'], name='support_tic_clinic__555d33_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-priority'], name='support_tic_status_be432d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='support_tic_assigne_6ed26f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_tic_ticket__e3cc1d_idx'),
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='support_ticket',
        ),
        migrations.AlterModelTable(
            name='ticketmessage',
            table='support_ticket_message',
        ),
    ]
