# Generated by Django 6.0.7 on 2026-07-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticket_options_alter_ticketmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='zoho_ticket_id',
            field=models.CharField(blank=True, help_text='ID do ticket no Zoho Desk (para sincronização)', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notion_page_id',
            field=models.CharField(blank=True, help_text='LEGADO — UUID da página no Notion. Campo mantido só para referência histórica de tickets criados antes da migração para Zoho Desk (BACFF-AVULSA-07); não é mais escrito nem sincronizado.', max_length=255),
        ),
    ]
