# Generated by Django 6.0.7 on 2026-07-27 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_clinic_desconto_fidelidade_ano2_and_more'),
        ('support', '0003_ticket_zoho_ticket_id_alter_ticket_notion_page_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('zoho_ticket_id', ''), _negated=True), fields=('zoho_ticket_id',), name='unique_non_empty_zoho_ticket_id'),
        ),
    ]
