# Generated by Django 6.0.7 on 2026-07-27 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_clinic_support_ticket_restricted_to_admin'),
        ('support', '0004_ticket_unique_non_empty_zoho_ticket_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reporter_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='EDGW-067 — identificador estável de QUEM abriu o chamado a partir do app desktop (o `sub` do JWT local do gateway, escopado à clínica). Não é um usuário do Backoffice (não há login de usuário aqui para o app desktop, só a clínica via license_key) — é opaco, não carrega PII, e serve só para o filtro de "Meus Chamados" (cada pessoa vê só os tickets que ela mesma abriu, nunca o board completo da clínica — ver views.py::list_my_error_reports). Fica em branco em tickets criados por outros caminhos (admin, support user).', max_length=64),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['clinic', 'reporter_user_id'], name='support_tic_clinic__401ec5_idx'),
        ),
    ]
