# Generated by Django 6.0.6 on 2026-06-28 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0004_add_cnpj_to_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_version', models.CharField(max_length=20)),
                ('os_info', models.CharField(blank=True, max_length=100)),
                ('db_size_mb', models.FloatField(default=0)),
                ('pending_sync', models.IntegerField(default=0)),
                ('sync_connected', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeat', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Heartbeat',
                'ordering': ['-last_seen'],
                'get_latest_by': 'last_seen',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Aviso'), ('error', 'Erro')], max_length=10)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Log do Sistema',
                'verbose_name_plural': 'Logs do Sistema',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
