# Generated by Django 6.0.6 on 2026-07-14 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0007_clinic_asaas_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TISSLote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_lote', models.PositiveIntegerField()),
                ('competencia', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('montando', 'Montando'), ('validado', 'Validado (XSD ok)'), ('enviando', 'Enviando'), ('enviado', 'Enviado (protocolo recebido)'), ('erro_envio', 'Erro no envio'), ('processado_aceito', 'Processado — aceito integralmente'), ('processado_glosa', 'Processado — com glosa')], default='montando', max_length=20)),
                ('xml_enviado', models.TextField(blank=True)),
                ('xml_recebido', models.TextField(blank=True)),
                ('protocolo', models.CharField(blank=True, max_length=20)),
                ('hash_epilogo', models.CharField(blank=True, max_length=32)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enviado_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiss_lotes', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Lote TISS',
                'verbose_name_plural': 'Lotes TISS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TISSGuia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.CharField(help_text='ID do agendamento no Edge Gateway (não é FK)', max_length=64)),
                ('tipo', models.CharField(default='sp-sadt', max_length=30)),
                ('numero', models.CharField(help_text='numeroGuiaPrestador', max_length=20)),
                ('competencia', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('nao_enviada', 'Não enviada'), ('enviada', 'Enviada'), ('aceita', 'Aceita'), ('glosada', 'Glosada'), ('parcial', 'Aceita parcialmente')], default='nao_enviada', max_length=20)),
                ('numero_carteira', models.CharField(blank=True, max_length=20)),
                ('beneficiario_nome', models.CharField(blank=True, max_length=70)),
                ('procedimentos', models.JSONField(blank=True, default=list)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiss_guias', to='clinics.clinic')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='tiss.tisslote')),
            ],
            options={
                'verbose_name': 'Guia TISS',
                'verbose_name_plural': 'Guias TISS',
            },
        ),
        migrations.CreateModel(
            name='TISSOperatorConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_operadora', models.CharField(max_length=70)),
                ('registro_ans', models.CharField(help_text='Registro ANS da operadora (6 dígitos)', max_length=6)),
                ('cnpj_operadora', models.CharField(blank=True, max_length=14)),
                ('endpoint_url', models.URLField(max_length=255)),
                ('login_encrypted', models.TextField(blank=True)),
                ('senha_encrypted', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiss_operator_configs', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Configuração de Operadora TISS',
                'verbose_name_plural': 'Configurações de Operadora TISS',
            },
        ),
        migrations.AddField(
            model_name='tisslote',
            name='operator_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='tiss.tissoperatorconfig'),
        ),
        migrations.CreateModel(
            name='TISSGlosa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('valor_glosado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recurso_enviado', models.BooleanField(default=False)),
                ('resposta', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosas', to='tiss.tissguia')),
            ],
            options={
                'verbose_name': 'Glosa TISS',
                'verbose_name_plural': 'Glosas TISS',
                'indexes': [models.Index(fields=['codigo'], name='tiss_tissgl_codigo_f444fb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tissguia',
            index=models.Index(fields=['clinic', 'competencia', 'status'], name='tiss_tissgu_clinic__ece7fc_idx'),
        ),
        migrations.AddIndex(
            model_name='tissguia',
            index=models.Index(fields=['clinic', 'appointment_id'], name='tiss_tissgu_clinic__34701a_idx'),
        ),
        migrations.AddIndex(
            model_name='tissoperatorconfig',
            index=models.Index(fields=['clinic', 'ativo'], name='tiss_tissop_clinic__b73913_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tissoperatorconfig',
            unique_together={('clinic', 'registro_ans')},
        ),
        migrations.AddIndex(
            model_name='tisslote',
            index=models.Index(fields=['clinic', 'competencia'], name='tiss_tisslo_clinic__b60564_idx'),
        ),
        migrations.AddIndex(
            model_name='tisslote',
            index=models.Index(fields=['clinic', 'status'], name='tiss_tisslo_clinic__aa7ca7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tisslote',
            unique_together={('clinic', 'operator_config', 'numero_lote')},
        ),
    ]
