# Generated by Django 6.0.6 on 2026-07-16 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_clinic_desconto_fidelidade_ano2_and_more'),
        ('tiss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TISSElegibilidadeConsulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.CharField(blank=True, help_text='ID do agendamento no Edge Gateway (não é FK, mesmo padrão de TISSGuia.appointment_id)', max_length=64)),
                ('numero_carteira', models.CharField(max_length=20)),
                ('beneficiario_nome', models.CharField(blank=True, max_length=70)),
                ('origem', models.CharField(choices=[('automatica', 'Automática (SOAP)'), ('manual', 'Manual (recepção)')], default='automatica', max_length=10)),
                ('elegivel', models.BooleanField()),
                ('motivos_negativa', models.JSONField(blank=True, default=list, help_text='Lista de {codigo, descricao} quando elegivel=False')),
                ('numero_guia_operadora', models.CharField(blank=True, max_length=20)),
                ('xml_enviado', models.TextField(blank=True)),
                ('xml_recebido', models.TextField(blank=True)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiss_elegibilidade_consultas', to='clinics.clinic')),
                ('operator_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elegibilidade_consultas', to='tiss.tissoperatorconfig')),
            ],
            options={
                'verbose_name': 'Consulta de Elegibilidade TISS',
                'verbose_name_plural': 'Consultas de Elegibilidade TISS',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'numero_carteira'], name='tiss_tissel_clinic__64c9e5_idx'), models.Index(fields=['clinic', 'created_at'], name='tiss_tissel_clinic__dd5938_idx'), models.Index(fields=['clinic', 'appointment_id'], name='tiss_tissel_clinic__42132a_idx')],
            },
        ),
    ]
