# Generated by Django 6.0.6 on 2026-07-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiss', '0002_tisselegibilidadeconsulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANSInsuranceOperator',
            fields=[
                ('ans_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=14)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Usado pelo gateway para invalidar cache local quando a ANS atualizar este registro')),
            ],
            options={
                'verbose_name': 'Operadora ANS (referência)',
                'verbose_name_plural': 'Operadoras ANS (referência)',
            },
        ),
        migrations.CreateModel(
            name='TUSSProcedureCode',
            fields=[
                ('tuss_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('table_code', models.CharField(default='22', help_text="'22'=médico, '90'=odontológico", max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Usado pelo gateway para invalidar cache local quando a ANS atualizar este registro')),
            ],
            options={
                'verbose_name': 'Código TUSS (referência)',
                'verbose_name_plural': 'Códigos TUSS (referência)',
                'indexes': [models.Index(fields=['table_code'], name='tiss_tusspr_table_c_1e76b0_idx')],
            },
        ),
    ]
