# Generated by Django 6.0.6 on 2026-07-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_clinic_desconto_fidelidade_ano2_and_more'),
        ('tiss', '0005_seed_tuss22_completo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tisselegibilidadeconsulta',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log de Consulta de Elegibilidade TISS', 'verbose_name_plural': 'Logs de Consulta de Elegibilidade TISS'},
        ),
        migrations.RemoveIndex(
            model_name='tisselegibilidadeconsulta',
            name='tiss_tissel_clinic__64c9e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='tisselegibilidadeconsulta',
            name='tiss_tissel_clinic__42132a_idx',
        ),
        migrations.AddField(
            model_name='tisselegibilidadeconsulta',
            name='status',
            field=models.CharField(choices=[('sucesso', 'Sucesso (resposta recebida da operadora)'), ('falha_transporte', 'Falha de transporte (SOAP)'), ('falha_operadora', 'Operadora rejeitou a própria consulta')], default='sucesso', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tisselegibilidadeconsulta',
            name='appointment_id',
            field=models.CharField(blank=True, help_text='ID do agendamento no Edge Gateway (não é FK, mesmo padrão de TISSGuia.appointment_id) — referência opaca, não é PII por si só', max_length=64),
        ),
        migrations.AddIndex(
            model_name='tisselegibilidadeconsulta',
            index=models.Index(fields=['clinic', 'status'], name='tiss_tissel_clinic__5c636d_idx'),
        ),
        migrations.RemoveField(
            model_name='tisselegibilidadeconsulta',
            name='beneficiario_nome',
        ),
        migrations.RemoveField(
            model_name='tisselegibilidadeconsulta',
            name='elegivel',
        ),
        migrations.RemoveField(
            model_name='tisselegibilidadeconsulta',
            name='motivos_negativa',
        ),
        migrations.RemoveField(
            model_name='tisselegibilidadeconsulta',
            name='numero_carteira',
        ),
        migrations.RemoveField(
            model_name='tisselegibilidadeconsulta',
            name='numero_guia_operadora',
        ),
        migrations.RemoveField(
            model_name='tisselegibilidadeconsulta',
            name='xml_enviado',
        ),
        migrations.RemoveField(
            model_name='tisselegibilidadeconsulta',
            name='xml_recebido',
        ),
    ]
