# Generated by Django 6.0.7 on 2026-07-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiss', '0006_elegibilidade_remove_pii_do_banco_central'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissoperatorconfig',
            name='gateway_provider',
            field=models.CharField(choices=[('generico_ans', 'Genérico (padrão ANS)'), ('orizon', 'Orizon (Autorize)')], default='generico_ans', help_text='Qual client SOAP usar para esta operadora (genérico ANS ou hub específico como Orizon)', max_length=20),
        ),
    ]
