# Generated by Django 6.0.7 on 2026-07-28 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_clinic_support_ticket_restricted_to_admin'),
        ('tiss', '0008_gateway_provider_desconhecido'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorCallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registro_ans', models.CharField(help_text='Chave de agregação genérica — nunca o nome do gateway', max_length=6)),
                ('gateway_provider', models.CharField(choices=[('desconhecido', 'Desconhecido (não confirmado — bloqueia chamada automática)'), ('generico_ans', 'Genérico (padrão ANS) — só com compatibilidade confirmada'), ('orizon', 'Orizon (Autorize)')], max_length=20)),
                ('operation', models.CharField(choices=[('cobertura', 'Cobertura (elegibilidade/autorização)'), ('envio_lote', 'Envio de lote')], max_length=20)),
                ('outcome', models.CharField(choices=[('success', 'Sucesso'), ('soap_fault', 'Operadora rejeitou a requisição'), ('network_error', 'Falha de rede/transporte'), ('provider_error', 'Erro estrutural de provider')], max_length=20)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiss_operator_calls', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Log de Chamada à Operadora',
                'verbose_name_plural': 'Logs de Chamada à Operadora',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['registro_ans', 'created_at'], name='tiss_operat_registr_6320d1_idx'), models.Index(fields=['clinic', 'created_at'], name='tiss_operat_clinic__5504da_idx')],
            },
        ),
    ]
