# Generated by Django 6.0.7 on 2026-07-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiss', '0012_tissoperatorconfig_remove_transport_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissguia',
            name='indicacao_clinica',
            field=models.CharField(blank=True, help_text='CID/indicação clínica da guia (usado no <indicacaoClinica> do Autorize Orizon)', max_length=500),
        ),
    ]
