# Generated by Django 6.0.7 on 2026-07-30 02:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_clinic_support_ticket_restricted_to_admin'),
        ('tiss', '0013_tissguia_indicacao_clinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='TISSDocumentoAssinatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pendente_assinatura', 'Pendente de assinatura (aguardando gateway)'), ('assinado', 'Assinado (bloco recebido, pronto para transmitir)'), ('enviado', 'Enviado (protocolo recebido da operadora)'), ('erro_envio', 'Erro no envio')], default='pendente_assinatura', max_length=20)),
                ('fragmento_canonico', models.TextField()),
                ('root_tag', models.CharField(help_text='Nome qualificado da tag raiz (ex.: sch:envioDocumentoWS) — usado só para achar o ponto de inserção textual do bloco de assinatura, nunca para reparsear o fragmento.', max_length=100)),
                ('sequencial_transacao', models.CharField(blank=True, max_length=20)),
                ('signature_block', models.TextField(blank=True)),
                ('xml_final', models.TextField(blank=True)),
                ('protocolo', models.CharField(blank=True, max_length=20)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assinado_at', models.DateTimeField(blank=True, null=True)),
                ('enviado_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiss_documentos_assinatura', to='clinics.clinic')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_assinatura', to='tiss.tissguia')),
                ('operator_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_assinatura', to='tiss.tissoperatorconfig')),
            ],
            options={
                'verbose_name': 'Documento TISS pendente de assinatura (XMLDSig)',
                'verbose_name_plural': 'Documentos TISS pendentes de assinatura (XMLDSig)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'status'], name='tiss_tissdo_clinic__863e44_idx')],
            },
        ),
    ]
