# Generated by Django 6.0.7 on 2026-07-30 02:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_clinic_support_ticket_restricted_to_admin'),
        ('tiss', '0013_tissguia_indicacao_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorcalllog',
            name='operation',
            field=models.CharField(choices=[('cobertura', 'Cobertura (elegibilidade/autorização)'), ('envio_lote', 'Envio de lote'), ('cancelamento', 'Cancelamento de guia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tissguia',
            name='status',
            field=models.CharField(choices=[('nao_enviada', 'Não enviada'), ('enviada', 'Enviada'), ('aceita', 'Aceita'), ('glosada', 'Glosada'), ('parcial', 'Aceita parcialmente'), ('cancelada', 'Cancelada')], default='nao_enviada', max_length=20),
        ),
        migrations.CreateModel(
            name='TISSCancelamentoPendente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('falhou_apos_retries', models.BooleanField(default=False, help_text='True quando as 3 tentativas de retry do Celery se esgotaram sem sucesso — precisa de ação manual.')),
                ('ultimo_erro', models.TextField(blank=True)),
                ('resolvido', models.BooleanField(default=False, help_text='Marcar quando o suporte reconciliar manualmente com a operadora.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiss_cancelamentos_pendentes', to='clinics.clinic')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelamentos_pendentes', to='tiss.tissguia')),
            ],
            options={
                'verbose_name': 'Cancelamento de Guia Pendente (alerta)',
                'verbose_name_plural': 'Cancelamentos de Guia Pendentes (alertas)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'falhou_apos_retries'], name='tiss_tissca_clinic__9196ff_idx'), models.Index(fields=['clinic', 'resolvido'], name='tiss_tissca_clinic__c1ffbf_idx')],
            },
        ),
    ]
