# Generated by Django 6.0.7 on 2026-07-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiss', '0014_alter_operatorcalllog_operation_and_more'),
        ('tiss', '0014_tissdocumentoassinatura'),
    ]

    operations = [
    ]
