# Generated by Django 6.0.7 on 2026-08-07 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_clinic_support_ticket_restricted_to_admin'),
        ('tiss', '0015_merge_20260730_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorcalllog',
            name='operation',
            field=models.CharField(choices=[('cobertura', 'Cobertura (elegibilidade/autorização)'), ('envio_lote', 'Envio de lote'), ('cancelamento', 'Cancelamento de guia'), ('consulta_status', 'Consulta de status de autorização')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tisselegibilidadeconsulta',
            name='status',
            field=models.CharField(choices=[('sucesso', 'Sucesso (resposta recebida da operadora)'), ('falha_transporte', 'Falha de transporte (SOAP)'), ('falha_operadora', 'Operadora rejeitou a própria consulta'), ('em_analise', 'Em análise (aguardando confirmação da operadora)')], max_length=20),
        ),
        migrations.CreateModel(
            name='TISSAutorizacaoPendente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.CharField(blank=True, help_text='ID do agendamento no Edge Gateway (não é FK) — referência opaca, pode estar vazio para consultas avulsas', max_length=64)),
                ('numero_guia_prestador', models.CharField(help_text='numeroGuiaPrestador — chave usada para consultar o status depois', max_length=20)),
                ('numero_guia_operadora', models.CharField(blank=True, max_length=20)),
                ('situacao', models.CharField(choices=[('em_analise', 'Em análise (aguardando operadora)'), ('autorizado', 'Autorizado'), ('negado', 'Negado')], default='em_analise', max_length=20)),
                ('codigo_glosa', models.CharField(blank=True, max_length=10)),
                ('descricao_glosa', models.CharField(blank=True, max_length=500)),
                ('tentativas_consulta', models.PositiveIntegerField(default=0)),
                ('ultima_consulta_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_erro_consulta', models.TextField(blank=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiss_autorizacoes_pendentes', to='clinics.clinic')),
                ('operator_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes_pendentes', to='tiss.tissoperatorconfig')),
            ],
            options={
                'verbose_name': 'Autorização TISS Pendente',
                'verbose_name_plural': 'Autorizações TISS Pendentes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resolvido'], name='tiss_tissau_resolvi_085eab_idx'), models.Index(fields=['clinic', 'situacao'], name='tiss_tissau_clinic__48ea36_idx')],
                'unique_together': {('clinic', 'operator_config', 'numero_guia_prestador')},
            },
        ),
    ]
