# Generated by Django 6.0.7 on 2026-08-21 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiss', '0016_alter_operatorcalllog_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissoperatorconfig',
            name='ans_operator',
            field=models.ForeignKey(blank=True, help_text='Selecione uma operadora já cadastrada na tabela de referência ANS para preencher automaticamente nome/registro ANS/CNPJ abaixo, sem redigitar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_configs', to='tiss.ansinsuranceoperator'),
        ),
    ]
